name: Build and Test
on:
  push
permissions:
  id-token: write
  contents: read

jobs:
  worflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16.8
      - name: Install deps
        run: |
          export GOPATH=$(go env GOROOT)
          go mod download
          go mod vendor
          go get -u github.com/jstemmer/go-junit-report
          which go-junit-report
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.28
