name: Lint and Test
on:
  pull_request:
  push:
    branches:
      - master
permissions:
  id-token: write
  contents: read

jobs:
  worflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check out actions
        uses: actions/checkout@v2
        with:
          repository: infura/ghaction-packed
          token: ${{ secrets.JENKINS_INF_ACTIONS_PRIVATE_REPO_READ_TOKEN }}
          ref: v0.0.3
          path: .ghaction-packed
      - name: Lint and Test
        uses: ./.ghaction-packed/go/zeroconfig
        with:
          go_version: 1.16.8
