name: Lint and Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  review:
    name: "Linting && Unit Test"
    uses: consensys/github-toolkit/.github/workflows/go_review.yml@v1
    with:
      go_version: 1.17
    secrets:
      GH_READ_ONLY_TOKEN: ${{ secrets.INFURA_ORG_REPO_READ_ONLY }}
