name: Lint and Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  review:
    name: "Linting && Unit Test"
    uses: consensys/github-toolkit/.github/workflows/go_review.yml@v2
    with:
      go_version: 1.17
    secrets:
      GH_READ_APP_ID: ${{ secrets._GITHUB_READ_APP_ID }}
      GH_READ_APP_PRIVATE_KEY: ${{ secrets._GITHUB_READ_APP_PRIVATE_KEY }}
